### ISSUE TITLE
error handling hint

### ISSUE THREAD

**Issue by vitaly-t** [banerjs/blog#1]
from your `database.js`:

``` js
if (!!err.message
                                && err.message.toLowerCase().indexOf("no data") > -1) {
                            err.status = 404;
                        }
```

The right way to handle it would be:

a) If returning nothing is an expected result, you should use method `oneOrNone` instead, and then check the result for `null/undefined`.

b) If no result is really an error, the condition within the catch should be:

``` js
var pgp = require("pg-promise")(/*options*/);
var db = pgp("connection string...");

db.one("select...")
    .catch(function (error) {
        if (error instanceof pgp.QueryResultError) {
            err.status = 404;
        }
    });
```

**Comment by banerjs** [comment]
Oh interesting. I must have missed the `oneOrNone` method. Thanks for letting me know about it. I'll fix this for my next push.

BTW, I'm impressed with pg-promise, and even more impressed by the fact that you caught my push. Do you have some kind of GitHub hook notifying you of the use of pg-promise? Anyway, standby for the change.

**Comment by vitaly-t** [comment]
GitHub search is showing newcomers and pushes of all projects that use the library, I look at it sometimes :)

And you are welcome!
